MengeTroue/MengeTroue/Models/DbHandler.cs
using MengeTroue.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MengeTroue.Models
{
    public class DbHandler
    {
        public ApplicationDbContext _DbContext;
        public DbHandler(ApplicationDbContext DbContext)
        {
            _DbContext = DbContext;
        }

        public async Task PostRSVP(RSVP NewRSVP)
        {
            _DbContext.RSVPs.Add(NewRSVP);
            await _DbContext.SaveChangesAsync();
        }

        public async Task PostMessage(Message NewMessage)
        {
            _DbContext.Messages.Add(NewMessage);
            await _DbContext.SaveChangesAsync();
        }

        public List<RSVP> GetAllRSVPs()
        {
            var test = _DbContext.RSVPs.ToList();
            return _DbContext.RSVPs.ToList();

        }

        public List<Message> GetAllMessages()
        {

            var test = _DbContext.Messages.ToList();
            return _DbContext.Messages.ToList();

        }
    }
}

MengeTroue/MengeTroue/Models/Message.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace MengeTroue.Models
{
    public class Message
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public string Email { get; set; }
        public string MessageContent { get; set; }
    }
}

MengeTroue/MengeTroue/Models/RSVP.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;


namespace MengeTroue.Models
{
    public class RSVP
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public string Email { get; set; }
        public string Attending { get; set; }
        public string AttendingDays { get; set; }
        public string SongRequest { get; set; }
        public string Note { get; set; }

    }
}

MengeTroue/MengeTroue/Pages/CustomPages/Admin.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MengeTroue.Data;
using MengeTroue.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MengeTroue.Pages.CustomPages
{
    [Authorize]
    public class AdminModel : PageModel
    {
        ApplicationDbContext _DbContext;
        DbHandler _DbHandler;

        [BindProperty]
        public List<RSVP> AllRSVPS { get; set; }
        [BindProperty]
        public List<Message> AllMessages { get; set; }
        public AdminModel(ApplicationDbContext DbContext)
        {
            _DbHandler =  new DbHandler(DbContext);
        }
        public void OnGet()
        {
            AllRSVPS =  _DbHandler.GetAllRSVPs();
            AllMessages = _DbHandler.GetAllMessages();
        }
    }
}

MengeTroue/MengeTroue/Pages/CustomPages/Home.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MengeTroue.Data;
using MengeTroue.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MengeTroue.Pages.CustomPages
{
    public class HomeModel : PageModel
    {
        [BindProperty]
        public RSVP _RSVP { get; set; }

        [BindProperty]
        public Message _Message { get; set; }

        public ApplicationDbContext _DbContext;
        public DbHandler _DbHandler;
        public EmailHandler _EmailHandler;

        public HomeModel(ApplicationDbContext DbContext)
        {
            _DbContext = DbContext;
            _DbHandler = new DbHandler(_DbContext);
            _EmailHandler = new EmailHandler();
        }

        public async Task<IActionResult> OnPostRSVPAsync()
        {
            await _DbHandler.PostRSVP(_RSVP);
            _EmailHandler.SendRSVP(_RSVP);


            return RedirectToPage("Home");
        }

        public async Task<IActionResult> OnPostMessageAsync()
        {
            await _DbHandler.PostMessage(_Message);
            _EmailHandler.SendMessage(_Message);
            
            return RedirectToPage("Home");
        }


        public void OnGet()
        {
        }
    }
}

MengeTroue/MengeTroue/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MengeTroue.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

MengeTroue/MengeTroue/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MengeTroue.Pages
{
    public class IndexModel : PageModel
    {
        public IActionResult OnGet()
        {
            return Redirect("/Home");
        }
    }
}

MengeTroue/MengeTroue/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MengeTroue.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

MengeTroue/MengeTroue/Pages/CustomPages/Admin.cshtml
@page "/Admin"
@model MengeTroue.Pages.CustomPages.AdminModel
@{
    ViewData["Title"] = "Admin";
}

<style>
    .TableDiv {
        width: 80vw;
        margin: auto;
    }

    .TableButtons {
        width: 50vw;
        height: 5vw;
    }
</style>


<div class="TableDiv">
    <button class="TablesButton" onclick="ShowRSVPS()">RSVPS</button>
    <button class="TablesButton" onclick="ShowMessages()">MESSAGES</button>
    <h2 id="TableHeading">RSVPS</h2>

    <div id="RSVPTable" >
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Attending</th>
                    <th>AttendingDays</th>
                    <th>Email</th>
                    <th>Song Request</th>
                    <th>Note</th>
                </tr>
            </thead>
            <tbody>

                @{
                    for (int i = 0; i < Model.AllRSVPS.Count; i++)
                    {
                <tr>
                    <td>@Model.AllRSVPS[i].Id</td>
                    <td>@Model.AllRSVPS[i].Name</td>
                    <td>@Model.AllRSVPS[i].Attending</td>

                    @if (Model.AllRSVPS[i].AttendingDays != "None")
                    {
                        <td>@Model.AllRSVPS[i].AttendingDays</td>
                    }
                    else
                    {
                        <td>-</td>
                    }

                    <td>@Model.AllRSVPS[i].Email</td>
                    <td>@Model.AllRSVPS[i].SongRequest</td>
                    <td>@Model.AllRSVPS[i].Note</td>
                </tr>
                    }

                }
            </tbody>
        </table>
    </div>

    <div id="MessagesTable" hidden>
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Number</th>
                    <th>Message</th>
                </tr>
            </thead>
            <tbody>
                @{
                    for (int i = 0; i < Model.AllMessages.Count; i++)
                    {
                        <tr>
                            <td>@Model.AllMessages[i].Id</td>
                            <td>@Model.AllMessages[i].Name</td>
                            <td>@Model.AllMessages[i].Email</td>
                            <td>@Model.AllMessages[i].Number</td>
                            <td>@Model.AllMessages[i].MessageContent</td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>

<script>
    function ShowRSVPS() {
        document.getElementById('MessagesTable').hidden = true;
        document.getElementById('RSVPTable').hidden = false;

        document.getElementById('TableHeading').innerHTML = 'RSVPS';
   
    }

    function ShowMessages() {
        document.getElementById('MessagesTable').hidden = false;
        document.getElementById('RSVPTable').hidden = true;

        document.getElementById('TableHeading').innerHTML = 'Messages';
    }

</script>

MengeTroue/MengeTroue/Pages/CustomPages/_ContactUs.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model MengeTroue.Pages.CustomPages.HomeModel

<style>

    .ContactUsDiv {
        height: 42vw;
        margin: auto;
        margin-top: 1vw;
        width: 60vw;
        border: 3px solid #b1b881;
        padding: 1vw;
        border-radius: 15px;
    }

    .ContactUsTitleDiv {
        height: 5vw;
        margin: auto;
        margin-top: 0.5vw;
        width: 30vw;
        padding: 1vw;
    }

    .ContactUsTitleLabel {
        font-size: 2vw;
        height: 100%;
        margin: auto;
        margin-top: 1vw;
        color: #b1b881;
    }

    .ContactUsSubTitleLabel {
        font-size: 1.15vw;
        height: 100%;
        margin: auto;
        margin-top: 1vw;
        color: #d7d7d7;
    }


    .ContactUsInputDiv {
        width: 90%;
        margin: auto;
    }

    .ContactUsInputLabels {
        margin: 1vw;
        margin-bottom: 0px;
    }

    .ContactUsInputs {
        width: 100%;
        margin: 1vw;
        height: 3vw;
        margin-top: 0.5vw;
        border: 3px solid #b1b881;
        font-size: 1.25vw;
        padding: 1vw;
        border-radius: 10px;
    }

    .ContactUsSubmitButton {
        height: 3vw;
        width: 7vw;
        margin-top: 5%;
        border: 3px solid #b1b881;
        border-radius: 15px;
        background-color: #b1b881;
    }

    .ContactUsSubmitButtonSpan {
        color: #FFF;
    }


    .ContactUsTextArea {
        border-radius: 15px;
        border: 3px solid #b1b881;
        margin: 1vw;
        width: 100%;
    }



    @@media only screen and (max-width: 600px) {

        .ContactUsDiv {
            height: 135vw;
            margin: auto;
            margin-top: 0vw;
            width: 95vw;
            border: 3px solid #b1b881;
            padding: 5vw;
        }

        .ContactUsTitleDiv {
            height: 5vh;
            margin: auto;
            margin-top: 5vh;
            width: 60vw;
            padding: 10px;
        }

        .ContactUsTitleLabel {
            font-size: 7vw;
            height: 100%;
            margin: auto;
            margin-top: 2vh;
            color: #b1b881;
        }

        .ContactUsSubTitleLabel {
            font-size: 4vw;
            height: 100%;
            margin: auto;
            margin-top: 2vh;
            color: #d7d7d7;
        }


        .ContactUsInputDiv {
            width: 90%;
            margin: auto;
        }

        .ContactUsInputLabels {
            margin: 1vw;
            margin-bottom: 0px;
        }

        .ContactUsInputs {
            width: 100%;
            margin: 1vw;
            height: 12vw;
            margin-top: 1vh;
            border: 3px solid #b1b881;
            font-size: 5vw;
            padding: 2vw;
            border-radius: 10px;
        }

        .ContactUsSubmitButton {
            height: 10vw;
            width: 20vw;
            margin-top: 5%;
            border: 3px solid #b1b881;
            border-radius: 15px;
            background-color: #b1b881;
        }

        .ContactUsSubmitButtonSpan {
            color: #FFF;
        }
    }
</style>
<meta name="viewport" content="width=device-width, initial-scale=1" />




<div class="row" style="height:150px;">

    <div class="ContactUsTitleDiv">

        <div class="row" style="height:50px;">
            <label class="ContactUsTitleLabel">Contact Us</label>
        </div>
        <div class="row" style="height:50px;">
            <label class="ContactUsSubTitleLabel">For any questions or concerns</label>
        </div>
    </div>
</div>
<form method="post"  asp-page-handler="Message" id="ContactUsForm">
    <div class="ContactUsDiv">

        <div class="row">
            <div class="ContactUsInputDiv">
                <div class="row">
                    <label class="ContactUsInputLabels">YOUR NAME AND SURNAME</label>
                </div>
                <div class="row">
                    <input type="text" class="ContactUsInputs" id="ContactUsName" asp-for="@Model._Message.Name">
                </div>
            </div>
        </div>

        <div class="row">
            <div class="ContactUsInputDiv">
                <div class="row">
                    <label class="ContactUsInputLabels">YOUR NUMBER</label>
                </div>
                <div class="row">
                    <input type="text" class="ContactUsInputs" id="ContactUsNumber" asp-for="@Model._Message.Number">
                </div>
            </div>
        </div>

        <div class="row">
            <div class="ContactUsInputDiv">
                <div class="row">
                    <label class="ContactUsInputLabels">YOUR EMAIL (Optional)</label>
                </div>
                <div class="row">
                    <input type="text" class="ContactUsInputs" id="ContactUsEmail" asp-for="@Model._Message.Email">
                </div>
            </div>
        </div>

        <div class="row">
            <div class="ContactUsInputDiv">
                <div class="row">
                    <label class="ContactUsInputLabels">YOUR MESSAGE</label>
                </div>
                <div class="row">
                    <textarea id="ContactUsMessage" class="ContactUsTextArea" rows="5" cols="20" wrap="hard" asp-for="@Model._Message.MessageContent">  </textarea>

                </div>
            </div>
        </div>

        <div class="row">
            <div class="ContactUsInputDiv">
                <button class="ContactUsSubmitButton" type="button" onclick="SubmitContactForm()">
                    <span class="ContactUsSubmitButtonSpan">
                        Submit
                    </span>

                </button>
            </div>
        </div>


    </div>
</form>

<script>
    function SubmitContactForm() {
        var ContactFormValid = true;


        var ContactUsName = document.getElementById('ContactUsName');
        var ContactUsNumber = document.getElementById('ContactUsNumber');
        //var ContactUsName = document.getElementById('ContactUsEmail');
        var ContactUsMessage = document.getElementById('ContactUsMessage');

        if (ContactUsName.value == '') {
            ContactUsName.style = 'border:3px solid red;'
            ContactFormValid = false;
        }

        if (ContactUsNumber.value == '') {
            ContactUsNumber.style = 'border:3px solid red;'
            ContactFormValid = false;
        }

        if (ContactUsMessage.value == '') {
            ContactUsMessage.style = 'border:3px solid red;'
            ContactFormValid = false;
        }

        if (ContactFormValid == true) {
            if (!confirm('Your message has been submitted successfully')) { return false; }
            document.getElementById('ContactUsForm').submit();
        }


    }

</script>

MengeTroue/MengeTroue/Pages/CustomPages/_Invite.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<style>
    .InviteDiv {
        margin: auto;
        margin-top: 5vw;
        width: 45vw;
        height: 55vw;
        border: 3px solid #b1b881;
        border-radius:15px;
    }

    @@media only screen and (max-width: 600px) {

        .InviteDiv {
            margin: auto;
            margin-top: 10vw;
            width: 100vw;
            height: 140vw;
        }
    
    }

</style>
<div class="InviteDiv">
    <img src="~/img/Invitejpeg.jpeg" />

</div>

MengeTroue/MengeTroue/Pages/CustomPages/_RSVP.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model MengeTroue.Pages.CustomPages.HomeModel
<style>

    .RSVPDiv {
        height: 50vw;
        margin: auto;
        margin-top: 1vw;
        width: 30vw;
        border: 3px solid #b1b881;
        padding: 1vw;
        border-radius: 15px;
    }

    .RSVPTitleDiv {
        height: 5vw;
        margin: auto;
        margin-top: 0.5vw;
        width: 30vw;
        padding: 1vw;
    }

    .RSVPTitleLabel {
        font-size: 2vw;
        height: 100%;
        margin: auto;
        margin-top: 1vw;
        color: #b1b881;
    }

    .RSVPSubTitleLabel {
        font-size: 1.15vw;
        height: 100%;
        margin: auto;
        margin-top: 1vw;
        color: #d7d7d7;
    }


    .RSVPInputDiv {
        width: 90%;
        margin: auto;
    }

    .RSVPInputLabels {
        margin: 1vw;
        margin-bottom: 0px;
    }

    .RSVPInputs {
        width: 100%;
        margin: 1vw;
        height: 3vw;
        margin-top: 0.5vw;
        border: 3px solid #b1b881;
        font-size: 1.25vw;
        padding: 1vw;
        border-radius: 10px;
    }

    .RSVPSubmitButton {
        height: 3vw;
        width: 7vw;
        margin-top: 5%;
        border: 3px solid #b1b881;
        border-radius: 15px;
        background-color: #b1b881;
    }

    .RSVPSubmitButtonSpan {
        color: #FFF;
    }

    .DaysAttendingDiv {
        display: inline-block;
        margin-left: 6vw;
    }

    .AttendanceCheckboxes {
        display: inline-block;
        margin-right: 5vw;
    }


    @@media only screen and (max-width: 600px) {
        .RSVPDiv {
            height: 170vw;
            margin: auto;
            margin-top: 0vw;
            width: 95vw;
            border: 3px solid #b1b881;
            padding: 5vw;
            border-radius: 10px;
        }

        .RSVPTitleDiv {
            height: 5vh;
            margin: auto;
            margin-top: 5vh;
            width: 60vw;
            padding: 10px;
        }

        .RSVPTitleLabel {
            font-size: 7vw;
            height: 100%;
            margin: auto;
            margin-top: 2vh;
            color: #b1b881;
        }

        .RSVPSubTitleLabel {
            font-size: 4vw;
            height: 100%;
            margin: auto;
            margin-top: 2vh;
            color: #d7d7d7;
        }


        .RSVPInputDiv {
            width: 90%;
            margin: auto;
        }

        .RSVPInputLabels {
            margin: 1vw;
            margin-bottom: 0px;
        }

        .RSVPInputs {
            width: 100%;
            margin: 1vw;
            height: 12vw;
            margin-top: 1vh;
            border: 3px solid #b1b881;
            font-size: 5vw;
            padding: 1vw;
            border-radius: 10px;
        }

        .RSVPSubmitButton {
            height: 10vw;
            width: 20vw;
            margin-top: 5%;
            border: 3px solid #b1b881;
            border-radius: 15px;
            background-color: #b1b881;
        }

        .RSVPSubmitButtonSpan {
            color: #FFF;
        }


        .DaysAttendingDiv {
            margin-left: 13vw;
        }

        .AttendanceCheckboxes {
            display: inline-block;
            margin-right: 12vw;
        }
  
    }



</style>
<meta name="viewport" content="width=device-width, initial-scale=1" />

<div class="row" style="height:150px;">

    <div class="RSVPTitleDiv">

        <div class="row" style="height:50px;">
            <label class="RSVPTitleLabel"> Will you attend?</label>
        </div>
        <div class="row" style="height:50px;">
            <label class="RSVPSubTitleLabel"> Please sign your RSVP</label>
        </div>
    </div>
</div>

<div class="RSVPDiv">

    <form method="post" id="RSVPForm" asp-page-handler="RSVP">

        <div class="row">
            <div class="RSVPInputDiv">
                <div class="row">
                    <label class="RSVPInputLabels">YOUR NAME AND SURNAME</label>
                </div>
                <div class="row">
                    <input type="text" class="RSVPInputs" id="RSVPName" asp-for=@Model._RSVP.Name>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="RSVPInputDiv">
                <div class="row">
                    <label class="RSVPInputLabels">YOUR NUMBER</label>
                </div>
                <div class="row">
                    <input type="text" class="RSVPInputs" id="RSVPNumber" asp-for=@Model._RSVP.Number>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="RSVPInputDiv">
                <div class="row">
                    <label class="RSVPInputLabels">YOUR EMAIL (Optional)</label>
                </div>
                <div class="row">
                    <input type="text" class="RSVPInputs" id="RSVPEmail" asp-for=@Model._RSVP.Email>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="RSVPInputDiv" style="margin-left:10%;">
                <div class="row">
                    <label class="RSVPInputLabels" style="font-size:20px; margin-left:-1%;">Will you attend?</label>
                </div>


                <div id="AttendanceCheckboxes" class="AttendanceCheckboxes">
                    <div class="row">
                        <div class="checkbox " style="margin-top:15px;">
                            <label id="AttendingLabel"><input id="AttendingCheckbox" type="checkbox" class="RSVPCheckboxes" onclick="AttendingChecked()" value="">Yes, I'll be there</label>
                        </div>
                    </div>

                    <div class="row">
                        <div class="checkbox " style="margin-top:0px;">
                            <label id="NotAttendingLabel"><input id="NotAttendingCheckbox" type="checkbox" class="RSVPCheckboxes" onclick="NotAttendingChecked()" value="">Sorry, I can't come</label>
                        </div>

                    </div>
                </div>

                <div class="AttendanceCheckboxes" id="AttendanceDaysCheckboxes" hidden>
                    <div class="row">
                        <div class="checkbox " style="margin-top:15px;">
                            <label id="AttendingFridayLabel"><input id="AttendingFridayCheckbox" type="checkbox" class="RSVPCheckboxes" value="">For Friday</label>
                        </div>
                    </div>

                    <div class="row">
                        <div class="checkbox " style="margin-top:0px;">
                            <label id="AttendingSaturdayLabel"><input id="AttendingSaturdayCheckbox" type="checkbox" class="RSVPCheckboxes" value="">For Saturday</label>
                        </div>

                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="RSVPInputDiv">
                <div class="row">
                    <label class="RSVPInputLabels">SONG REQUEST (Optional)</label>
                </div>
                <div class="row">
                    <input type="text" class="RSVPInputs" id="pwd" asp-for=@Model._RSVP.SongRequest>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="RSVPInputDiv">
                <div class="row">
                    <label class="RSVPInputLabels">NOTE (Optional)</label>
                </div>
                <div class="row">
                    <input type="text" class="RSVPInputs" id="pwd" asp-for=@Model._RSVP.Note>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="RSVPInputDiv">
                <button class="RSVPSubmitButton" type="button" onclick="SubmitForm()">
                    <span class="RSVPSubmitButtonSpan">
                        SEND
                    </span>
                </button>
            </div>
        </div>
        <input id="AttendingInput" type="text"  asp-for=@Model._RSVP.Attending  hidden/>
        <input id="AttendingDaysInput" type="text"  asp-for=@Model._RSVP.AttendingDays hidden />

    </form>
</div>


<script>

    function SubmitForm() {
        var IsFormValid = true;

        if ((document.getElementById('AttendingFridayCheckbox').checked == true) && (document.getElementById('AttendingSaturdayCheckbox').checked == true)) {
            document.getElementById('AttendingDaysInput').value = 'Both';
        } else if (document.getElementById('AttendingFridayCheckbox').checked == true) {
            document.getElementById('AttendingDaysInput').value = 'Friday';
        } else if (document.getElementById('AttendingSaturdayCheckbox').checked == true) {
            document.getElementById('AttendingDaysInput').value = 'Saturday';
        } else {
            document.getElementById('AttendingDaysInput').value = 'None';
        }


        //validate data
        var RSVPName = document.getElementById('RSVPName');
        var RSVPNumber = document.getElementById('RSVPNumber');
        //var RSVPEmail = document.getElementById('RSVPEmail');
        var RSVPAttending = document.getElementById('AttendingCheckbox');
        var RSVPNotAttending = document.getElementById('NotAttendingCheckbox');

        var RSVPAttendingFriday = document.getElementById('AttendingFridayCheckbox');
        var RSVPAttendingSaturday = document.getElementById('AttendingSaturdayCheckbox');

        if (RSVPName.value == '') {
            IsFormValid = false;
            RSVPName.style = 'border: 3px solid red';
        }
        if (RSVPNumber.value == '') {
            IsFormValid = false;
            RSVPNumber.style = 'border: 3px solid red';
        }

        //if (RSVPEmail.value == '') {
        //    IsFormValid = false;
        //    RSVPEmail.style = 'border: 3px solid red';
        //}

        if ((RSVPAttending.checked == false) && (RSVPNotAttending.checked == false)) {
            document.getElementById('AttendingLabel').style = 'color:red';
            document.getElementById('NotAttendingLabel').style = 'color:red';
            IsFormValid = false;
        }

        if ((RSVPAttending.checked == true) && !(RSVPAttendingFriday.checked || RSVPAttendingSaturday.checked)) {
            document.getElementById('AttendingLabel').style = 'color:black';
            document.getElementById('NotAttendingLabel').style = 'color:black';

            document.getElementById('AttendingFridayLabel').style = 'color:red';
            document.getElementById('AttendingSaturdayLabel').style = 'color:red';
            IsFormValid = false;
        }

        if (IsFormValid == true) {
            if (!confirm('Your RSVP has been submitted successfully')) { return false; }
            document.getElementById('RSVPForm').submit();
        }


    }

    var Attending = document.getElementById('AttendingCheckbox');
    var NotAttending = document.getElementById('NotAttendingCheckbox');
    var AttendanceDaysCheckboxes = document.getElementById('AttendanceDaysCheckboxes');
    function AttendingChecked() {
        Attending = document.getElementById('AttendingCheckbox');
        NotAttending = document.getElementById('NotAttendingCheckbox');

        if (Attending.checked == true) {
            document.getElementById('AttendingInput').value = "Yes";
            document.getElementById('NotAttendingCheckbox').checked = false;
            AttendanceDaysCheckboxes.hidden = false;
        } else {
            document.getElementById('AttendingCheckbox').checked = false;
            AttendanceDaysCheckboxes.hidden = true;
        }

    }

    function NotAttendingChecked() {
        Attending = document.getElementById('AttendingCheckbox');
        NotAttending = document.getElementById('NotAttendingCheckbox');

        if (NotAttending.checked == true) {
            document.getElementById('AttendingInput').value = "No";
            document.getElementById('AttendingCheckbox').checked = false;
            AttendanceDaysCheckboxes.hidden = true;
        } else {
            document.getElementById('NotAttendingCheckbox').checked = false;
            AttendanceDaysCheckboxes.hidden = true;
        }

    }

</script>

MengeTroue/MengeTroue/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>